# Generated by Django 2.1.4 on 2018-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xfzauth', '0002_auto_20180628_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
