# Generated by Django 2.1.4 on 2018-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xfzauth', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
